# generated by cabal-rpm-2.1.5 --standalone
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

%global gitsnap 2f6dd29258e880dbb7effd57a829a0470d8da48b

#%%global ghc_major 9.4
#%%global ghc_name ghc%%{?ghc_major}

%global ghc_without_dynamic 1
%global ghc_without_shared 1
%undefine with_ghc_prof
%undefine with_haddock
%global without_prof 1
%global without_haddock 1
%global debug_package %{nil}

Name:           elm
Version:        0.19.1
# FIXME shortgit
Release:        1%{?dist}.git2f6dd29
Summary:        The `elm` command line interface

License:        BSD-3-Clause
Url:            https://elm-lang.org/
# Begin cabal-rpm sources:
#Source0:        https://github.com/elm/compiler/archive/refs/tags/%%{version}.tar.gz#/compiler-%%{version}.tar.gz
Source0:        https://github.com/elm/compiler/archive/%{gitsnap}.tar.gz
# End cabal-rpm sources
# https://github.com/elm/compiler/issues/2318
Patch0:         terminal-disable-StaticFiles.patch

# Begin cabal-rpm deps:
BuildRequires:  ghc-rpm-macros
%if %{defined ghc_name}
BuildRequires:  %{ghc_name}-devel
%else
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-HTTP-devel
BuildRequires:  ghc-SHA-devel
BuildRequires:  ghc-ansi-terminal-devel
BuildRequires:  ghc-ansi-wl-pprint-devel
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-binary-devel
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-edit-distance-devel
BuildRequires:  ghc-file-embed-devel
BuildRequires:  ghc-filelock-devel
BuildRequires:  ghc-filepath-devel
BuildRequires:  ghc-haskeline-devel
BuildRequires:  ghc-http-client-devel
BuildRequires:  ghc-http-client-tls-devel
BuildRequires:  ghc-http-types-devel
#BuildRequires:  ghc-language-glsl-devel
BuildRequires:  ghc-mtl-devel
BuildRequires:  ghc-network-devel
BuildRequires:  ghc-parsec-devel
BuildRequires:  ghc-process-devel
#BuildRequires:  ghc-raw-strings-qq-devel
BuildRequires:  ghc-scientific-devel
BuildRequires:  ghc-snap-core-devel
BuildRequires:  ghc-snap-server-devel
BuildRequires:  ghc-template-haskell-devel
BuildRequires:  ghc-time-devel
BuildRequires:  ghc-unordered-containers-devel
BuildRequires:  ghc-utf8-string-devel
BuildRequires:  ghc-vector-devel
BuildRequires:  ghc-zip-archive-devel
%endif
BuildRequires:  cabal-install > 1.18
%if %{undefined ghc_name}
# for missing dep 'prettyclass':
BuildRequires:  ghc-pretty-devel
%endif
# End cabal-rpm deps

%description
This includes commands like `elm make`, `elm repl`, and many others for helping
make Elm developers happy and productive.


%prep
# Begin cabal-rpm setup:
%setup -q -n compiler-%{gitsnap}
# End cabal-rpm setup
%patch -P0 -p1 -b .orig


%build
# Begin cabal-rpm build:
%global cabal_install %{_bindir}/cabal
%cabal_install update
%if 0%{?rhel} && 0%{?rhel} < 9
%cabal_install sandbox init
%cabal_install install
%endif
# End cabal-rpm build


%install
# Begin cabal-rpm install
mkdir -p %{buildroot}%{_bindir}
%if 0%{?fedora} || 0%{?rhel} >= 9
%ghc_set_gcc_flags
%cabal_install install %{?ghc_name:-w ghc-%{ghc_major}} --install-method=copy --enable-executable-stripping --installdir=%{buildroot}%{_bindir}
%else
for i in .cabal-sandbox/bin/*; do
strip -s -o %{buildroot}%{_bindir}/$(basename $i) $i
done
%endif
# End cabal-rpm install


%files
# Begin cabal-rpm files:
%license LICENSE
%doc README.md
%{_bindir}/%{name}
# End cabal-rpm files


%changelog
* Wed Nov 29 2023 Jens Petersen <petersen@redhat.com> - 0.19.1-1
- spec file generated by cabal-rpm-2.1.5
